export const APPLICATIONS = [
  {
    bidId: 1,
    projectName: 'Покровский бульвар, 4/17',
    number: '000 001',
    status: 'CREATED',
    fullProgress: 47,
    updatedDate: '13.08.2017',
  },
  {
    bidId: 2,
    projectName: 'ЖК «Спортивный комплекс Серебряническая набережная»',
    number: '000 002',
    status: 'COMPLETED',
    updatedDate: '02.11.2018',
    completedDate: '02.11.2018',
    banksTotal: 25,
    banksNew: 5,
  },
  {
    bidId: 3,
    projectName: 'Покровский бульвар, 4/17',
    number: '000 001',
    status: 'CREATED',
    fullProgress: 47,
    updatedDate: '13.08.2017',
  },
  {
    bidId: 4,
    projectName: 'ЖК «Спортивный комплекс Серебряническая набережная»',
    number: '000 002',
    status: 'COMPLETED',
    updatedDate: '02.11.2018',
    completedDate: '02.11.2018',
    banksTotal: 25,
    banksNew: 5,
  },
  {
    bidId: 5,
    projectName: 'Покровский бульвар, 4/17',
    number: '000 001',
    status: 'CREATED',
    fullProgress: 47,
    updatedDate: '13.08.2017',
  },
  {
    bidId: 6,
    projectName: 'ЖК «Спортивный комплекс Серебряническая набережная»',
    number: '000 002',
    status: 'COMPLETED',
    updatedDate: '02.11.2018',
    completedDate: '02.11.2018',
    banksTotal: 25,
    banksNew: 5,
  },
  {
    bidId: 7,
    projectName: 'Маросейка, 22',
    number: '000 003',
    status: 'COMPLETED',
    updatedDate: '02.11.2018',
    completedDate: '02.11.2018',
    banksTotal: 4,
    banksNew: 21,
  },
  {
    bidId: 8,
    projectName: 'ЖК «Спортивный комплекс Серебряническая набережная»',
    number: '000 002',
    status: 'COMPLETED',
    updatedDate: '02.11.2018',
    completedDate: '02.11.2018',
    banksTotal: 25,
    banksNew: 5,
  },
  {
    bidId: 9,
    projectName: 'Маросейка, 22',
    number: '000 003',
    status: 'CREATED',
    fullProgress: 99,
    updatedDate: '13.08.2017',
    completedDate: '02.11.2018',
  },
];

export const BANKS = [
  { id: 1, name: 'АКБ Российиский капитал', date: new Date() },
  { id: 2, name: 'Московский Кредитный Банк', date: new Date() },
  { id: 3, name: 'Хоум Кредит Банк' },
  {
    id: 4,
    name:
      'Уральский банк реконструкции и развития  «Серебряническая наб., 162 А» Объект не соотвествует признакам проблемности.',
  },
  { id: 5, name: 'Промсвязьбанк' },
  { id: 6, name: 'Российский капитал' },
  { id: 7, name: 'АКБ Российиский капитал', date: new Date() },
  { id: 8, name: 'АКБ Российиский капитал', date: new Date() },
  { id: 9, name: 'АКБ Российиский капитал', date: new Date() },
  { id: 10, name: 'АКБ Российиский капитал', date: new Date() },
  { id: 11, name: 'АКБ Российиский капитал', date: new Date() },
  { id: 12, name: 'АКБ Российиский капитал', date: new Date() },
];
